---
- name: First Play
  hosts: 27.27.27.213
  gather_facts: False
  connection: local
  tasks:
   - name: First Task
     ios_config:
       lines:
         - description - CONNECTED_INTERFACE_0/0/1_TO_SOLUTION_SW
         - ip address 192.192.1.1 255.255.255.252
         - no shutdown
       parents: interface tunnel 10
     register: version
   - name: Second Task
     debug:
       var: version
