---
- name: configure GRE at 4331
  hosts: 27.27.27.213
  gather_facts: False
  connection: local
  tasks:
   - name: First Task
     ios_config:
         lines:
           - ip address 100.100.100.1 255.255.255.252
           - tunnel source 10.10.10.10
           - tunnel destination 20.20.20.20
           - tunnel mode gre ip
           - description #GRE_TUNNEL_TO_1111#
           - no shutdown
         parents: interface tunnel 100
     register: version
   - name: Second Task
     debug:
       var: version

- name: configure GRE at 1111
  hosts: 27.27.27.209
  gather_facts: False
  connection: local
  tasks:
   - name: First Task
     ios_config:
         lines:
           - ip address 100.100.100.2 255.255.255.252
           - tunnel source 20.20.20.20
           - tunnel destination 10.10.10.10
           - tunnel mode gre ip
           - description #GRE_TUNNEL_TO_4331#
           - no shutdown
         parents: interface tunnel 100
     register: version
   - name: Second Task
     debug:
       var: version       
       
