---
- name: Cisco ISR 4331 Interface Configuation
  hosts: 27.27.27.213
  gather_facts: False
  connection: local
  tasks:
   - name: First Task
     ios_config:
       lines:
         - description - CONNECTED_INTERFACE_0/0/0_TO_HUAWEI_SW_Gi0/0/14
         - encapsulation dot1Q 165
         - ip address 192.192.1.1 255.255.255.252
         - no shutdown
       parents: interface Gigabitethernet0/0/0.165
     register: version
   - name: Second Task
     debug:
       var: version

- name: Cisco ISR 4331 LAN Interface Configuartion
  hosts: 27.27.27.213
  gather_facts: False
  connection: local
  tasks:
   - name: First Task
     ios_config:
       lines:
         - description - Cisco_4331_LAN_10
         - ip address 10.10.10.10 255.255.255.0
         - no shutdown
       parents: interface loopback10
     register: version
   - name: Second Task
     debug:
       var: version  
       
- name: Cisco ISR 1111 Interface Configuation
  hosts: 27.27.27.209
  gather_facts: False
  connection: local
  tasks:
   - name: First Task
     ios_config:
       lines:
         - description - CONNECTED_INTERFACE_0/0/0_TO_ACE_Fa0/20
         - encapsulation dot1Q 165
         - ip address 192.192.1.2 255.255.255.252
         - no shutdown
       parents: interface Gigabitethernet0/0/0.165
     register: version
   - name: Second Task
     debug:
       var: version

- name: Cisco ISR 1111 LAN Interface Configuartion
  hosts: 27.27.27.209
  gather_facts: False
  connection: local
  tasks:
   - name: First Task
     ios_config:
       lines:
         - description - Cisco_1111_LAN_20
         - ip address 20.20.20.20 255.255.255.0
         - no shutdown
       parents: interface loopback20
     register: version
   - name: Second Task
     debug:
       var: version         
     
- name: Cisco ISR 4331 BGP Configuartion
  hosts: 27.27.27.213
  gather_facts: False
  connection: local
  tasks:
   - name: First Task
     ios_config:
         lines:
         - neighbor 192.192.1.2 remote-as 64949
         - neighbor 192.168.10.1 description BGP_PEER_C1111
         - address-family ipv4
         - network 10.10.10.10 mask 255.255.255.255
         - neighbor 192.192.1.2 activate
         parents: router bgp 65534
     register: version
   - name: Second Task
     debug:
       var: version

- name: Cisco ISR 1111 BGP Configuartion
  hosts: 27.27.27.209
  gather_facts: False
  connection: local
  tasks:
   - name: First Task
     ios_config:
         lines:
         - neighbor 192.192.1.1 remote-as 65534
         - neighbor 192.168.10.1 description BGP_PEER_4331
         - address-family ipv4
         - network 20.20.20.0 mask 255.255.255.0
         - neighbor 192.192.1.1 activate
         parents: router bgp 64949
     register: version
   - name: Second Task
     debug:
       var: version  
       
- name: Cisco ISR 4331 IPSEC - Crypto Isakmp - Phase 1 Configuration
  hosts: 27.27.27.213
  gather_facts: False
  connection: local
  tasks:
   - name: First Task
     ios_config:
       lines:
         - encr 3des
         - hash md5
         - authentication pre-share
         - group 5
         - crypto isakmp key cisco123 address 192.192.1.2
         - crypto ipsec transform-set TS esp-3des esp-md5-hmac
       parents: crypto isakmp policy 10
     register: version
   - name: Second Task
     debug:
       var: version
       
- name: Cisco ISR 4331 IPSEC - Intresting Traffic - ACL Configuration
  hosts: 27.27.27.213
  gather_facts: False
  connection: local
  tasks:
   - name: First Task
     ios_config:
       lines:
         - permit ip 10.10.10.0 0.0.0.255 20.20.20.0 0.0.0.255
       parents: ip access-list extended VPN-TRAFFIC_1
     register: version
   - name: Second Task
     debug:
       var: version       

- name: Cisco ISR 4331 IPSEC - Crypto Map - Phase 2 Configuration
  hosts: 27.27.27.213
  gather_facts: False
  connection: local
  tasks:
   - name: First Task
     ios_config:
       lines:
         - set peer 192.192.1.2
         - set transform-set TS
         - match address VPN-TRAFFIC_1
       parents: crypto map CMAP 10 ipsec-isakmp
     register: version
   - name: Second Task
     debug:
       var: version
       
- name: Cisco ISR 4331 IPSEC - Crypto Mapping on WAN Interface
  hosts: 27.27.27.213
  gather_facts: False
  connection: local
  tasks:
   - name: First Task
     ios_config:
       lines:
         -  crypto map CMAP
       parents: interface Gi0/0/0.165
     register: version
   - name: Second Task
     debug:
       var: version       
       
- name: Cisco ISR 1111 IPSEC - Crypto Isakmp - Phase 1 Configuration
  hosts: 27.27.27.209
  gather_facts: False
  connection: local
  tasks:
   - name: First Task
     ios_config:
       lines:
         - encr 3des
         - hash md5
         - authentication pre-share
         - group 5
         - crypto isakmp key cisco123 address 192.192.1.1
         - crypto ipsec transform-set TS esp-3des esp-md5-hmac
       parents: crypto isakmp policy 10
     register: version
   - name: Second Task
     debug:
       var: version
       
- name: Cisco ISR 1111 IPSEC - Intresting Traffic - ACL Configuration
  hosts: 27.27.27.209
  gather_facts: False
  connection: local
  tasks:
   - name: First Task
     ios_config:
       lines:
         - permit ip 20.20.20.0 0.0.0.255 10.10.10.0 0.0.0.255
       parents: ip access-list extended VPN-TRAFFIC_1
     register: version
   - name: Second Task
     debug:
       var: version       

- name: Cisco ISR 1111 IPSEC - Crypto Map - Phase 2 Configuration
  hosts: 27.27.27.209
  gather_facts: False
  connection: local
  tasks:
   - name: First Task
     ios_config:
       lines:
         - set peer 192.192.1.1
         - set transform-set TS
         - match address VPN-TRAFFIC_1
       parents: crypto map CMAP 10 ipsec-isakmp
     register: version
   - name: Second Task
     debug:
       var: version
       
- name: Cisco ISR 1111 IPSEC - Crypto Mapping on WAN Interface
  hosts: 27.27.27.209
  gather_facts: False
  connection: local
  tasks:
   - name: First Task
     ios_config:
       lines:
         -  crypto map CMAP
       parents: interface Gi0/0/0.165
     register: version
   - name: Second Task
     debug:
       var: version


- name: Cisco ISR 4331 - BGP Status
  hosts: 27.27.27.213
  gather_facts: False
  connection: local
  tasks:
   - name: First Task
     ios_command:
         commands: Show ip bgp summary
     register: version
   - name: Second Task
     debug:
       var: version
       
- name: Cisco ISR 1111 - BGP Status
  hosts: 27.27.27.209
  gather_facts: False
  connection: local
  tasks:
   - name: First Task
     ios_command:
         commands: Show ip bgp summary
     register: version
   - name: Second Task
     debug:
       var: version       

- name: Cisco ISR 4331 - BGP Route details
  hosts: 27.27.27.213
  gather_facts: False
  connection: local
  tasks:
   - name: First Task
     ios_command:
         commands: show ip bgp 192.192.1.2
     register: version
   - name: Second Task
     debug:
       var: version
       
- name: Cisco ISR 1111 - BGP Route details
  hosts: 27.27.27.209
  gather_facts: False
  connection: local
  tasks:
   - name: First Task
     ios_command:
         commands: show ip bgp 192.192.1.1
     register: version
   - name: Second Task
     debug:
       var: version
       
- name: Cisco ISR 4331 - BGP  LAN Route details
  hosts: 27.27.27.213
  gather_facts: False
  connection: local
  tasks:
   - name: First Task
     ios_command:
         commands: show ip route 20.20.20.0
     register: version
   - name: Second Task
     debug:
       var: version
       
- name: Cisco ISR 1111 - BGP LAN Route details
  hosts: 27.27.27.213
  gather_facts: False
  connection: local
  tasks:
   - name: First Task
     ios_command:
         commands: show ip route 10.10.10.0
     register: version
   - name: Second Task
     debug:
       var: version
       
       
- name: Initiate Intresting Traffic to activate IPSEC Tunnel
  hosts: 27.27.27.213
  gather_facts: False
  connection: local
  tasks:
   - name: First Task
     ios_command:
         commands: Ping 20.20.20.20 source 10.10.10.10
         timeout: 15
     register: version
   - name: Second Task
     debug:
       var: version 
       
- name: Initiate Intresting Traffic to activate IPSEC Tunnel
  hosts: 27.27.27.213
  gather_facts: False
  connection: local
  tasks:
   - name: First Task
     ios_command:
         commands: Ping 20.20.20.20 source 10.10.10.10 timeout 15
     register: version
   - name: Second Task
     debug:
       var: version            
           
- name: Cisco ISR 4331 - IPSEC Tunnel Status
  hosts: 27.27.27.213
  gather_facts: False
  connection: local
  tasks:
   - name: First Task
     ios_command:
         commands: show crypto isakmp sa detail
     register: version
   - name: Second Task
     debug:
       var: version
       
- name: Cisco ISR 1111 - IPSEC Tunnel Status
  hosts: 27.27.27.209
  gather_facts: False
  connection: local
  tasks:
   - name: First Task
     ios_command:
         commands: show crypto isakmp sa detail
     register: version
   - name: Second Task
     debug:
       var: version

- name: Cisco ISR 4331 - IPSEC Tunnel Encrypted Traffic Details
  hosts: 27.27.27.213
  gather_facts: False
  connection: local
  tasks:
   - name: First Task
     ios_command:
         commands: show crypto ipsec sa peer 192.192.1.1 detail
     register: version
   - name: Second Task
     debug:
       var: version
       
- name: Cisco ISR 1111 - IPSEC Tunnel Encrypted Traffic Details
  hosts: 27.27.27.209
  gather_facts: False
  connection: local
  tasks:
   - name: First Task
     ios_command:
         commands: show crypto ipsec sa peer 192.192.1.1 detail
     register: version
   - name: Second Task
     debug:
       var: version
       
       
