---
- name: First Play
  hosts: 27.27.27.208
  gather_facts: False
  connection: local
  tasks:
   - name: First Task
     ios_config:
       lines:
         - description - CONNECTED_INTERFACE_0/0/0
       parents: interface Gigabitethernet0/0/0
     register: version
   - name: Second Task
     debug:
       var: version
       
- name: Second Play
  hosts: 27.27.27.208
  gather_facts: False
  connection: local
  tasks:
   - name: First Task
     ios_config:
       lines:
         - description - CONNECTED_INTERFACE_0/0/1
       parents: interface Gigabitethernet0/0/1
     register: version
   - name: Second Task
     debug:
       var: version
 
- name: Third Play
  hosts: 27.27.27.208
  gather_facts: False
  connection: local
  tasks:
   - name: First Task
     ios_config:
       lines:
         - description - CONNECTED_INTERFACE_0/0/0
       parents: interface Gigabitethernet0/0/0
     register: version
   - name: Second Task
     debug:
       var: version
       
- name: Fourth Play
  hosts: 27.27.27.208
  gather_facts: False
  connection: local
  tasks:
   - name: First Task
     ios_config:
       lines:
         - description - CONNECTED_INTERFACE_0/0/1
       parents: interface Gigabitethernet0/0/1
     register: version
   - name: Second Task
     debug:
       var: version
 
- name: Fifth Play
  hosts: 27.27.27.208
  gather_facts: False
  connection: local
  tasks:
   - name: First Task
     ios_command:
         commands: show interface description
     register: version
   - name: Second Task
     debug:
       var: version
       
   - name: Sixth Play
  hosts: 27.27.27.209
  gather_facts: False
  connection: local
  tasks:
   - name: First Task
     ios_command:
         commands: show interface description
     register: version
   - name: Second Task
     debug:
       var: version     
       
