---
- name: configure bgp
  hosts: 27.27.27.208
  gather_facts: False
  connection: local
  tasks:
   - name: First Task
     ios_config:
         lines:
         - neighbor 192.168.10.1 remote-as 4755
         - neighbor 192.168.10.1 description BGP_NEW
         - address-family ipv4
         - network 7.7.7.0 mask 255.255.255.0
         - neighbor 192.168.10.1 activate
         parents: router bgp 63345
     register: version
   - name: Second Task
     debug:
       var: version
