---
- name: First Play
  hosts: 27.27.27.213
  gather_facts: False
  connection: local
  tasks:
   - name: First Task
     cisco.ios.ios_l3_interfaces:
       config:
       - name: interface Gigabitethernet0/0/0.165
         ipv4:
         - address: 192.192.1.1/30
       state: merged
     register: version
   - name: Second Task
     debug:
       var: version

