---
- name: First Play
  hosts: 27.27.27.208
  gather_facts: False
  connection: local
  tasks:
   - name: First Task
     ios_config:
       lines:
         - description - #CONNECTED_INTERFACE_0/1/1#
       parents: interface GigabitEthernet0/1/1
     register: version
   - name: Second Task
     debug:
       var: version
