---
- name: Cisco iSR 4331 Interface Configuation
  hosts: 27.27.27.213
  gather_facts: False
  connection: local
  tasks:
   - name: First Task
     ios_config:
       lines:
         - description - #CONNECTED_INTERFACE_0/0/0_TO_HUAWEI_SW_Gi0/0/14#
         - encapsulation dot1Q 165
         - ip address 192.192.1.1 255.255.255.252
         - no shutdown
       parents: interface Gigabitethernet0/0/0.165
     register: version
   - name: Second Task
     debug:
       var: version

- name: Cisco iSR 4331 LAN Interface Configuartion
  hosts: 27.27.27.213
  gather_facts: False
  connection: local
  tasks:
   - name: First Task
     ios_config:
       lines:
         - description - #Cisco_4331_LAN_10#
         - ip address 10.10.10.10 255.255.255.0
         - no shutdown
       parents: interface loopback10
     register: version
   - name: Second Task
     debug:
       var: version  
       
- name: Cisco ISR 1111 Interface Configuation
  hosts: 27.27.27.209
  gather_facts: False
  connection: local
  tasks:
   - name: First Task
     ios_config:
       lines:
         - description - #CONNECTED_INTERFACE_0/0/0_TO_ACE_Fa0/20#
         - encapsulation dot1Q 165
         - ip address 192.192.1.2 255.255.255.252
         - no shutdown
       parents: interface Gigabitethernet0/0/0.165
     register: version
   - name: Second Task
     debug:
       var: version

- name: Cisco IR 1111 LAN Interface Configuartion
  hosts: 27.27.27.209
  gather_facts: False
  connection: local
  tasks:
   - name: First Task
     ios_config:
       lines:
         - description - #Cisco_1111_LAN_20#
         - ip address 20.20.20.20 255.255.255.0
         - no shutdown
       parents: interface loopback20
     register: version
   - name: Second Task
     debug:
       var: version         
     
 - name: Cisco ISR 4331 BGP Configuartion
  hosts: 27.27.27.213
  gather_facts: False
  connection: local
  tasks:
   - name: First Task
     ios_config:
         lines:
         - neighbor 192.192.1.2 remote-as 64949
         - neighbor 192.168.10.1 description BGP_PEER_C1111
         - address-family ipv4
         - network 10.10.10.10 mask 255.255.255.255
         - neighbor 192.192.1.2 activate
         parents: router bgp 65534
     register: version
   - name: Second Task
     debug:
       var: version

- name: Cisco ISR 1111 BGP Configuartion
  hosts: 27.27.27.209
  gather_facts: False
  connection: local
  tasks:
   - name: First Task
     ios_config:
         lines:
         - neighbor 192.192.1.1 remote-as 65534
         - neighbor 192.168.10.1 description BGP_PEER_4331
         - address-family ipv4
         - network 20.20.20.0 mask 255.255.255.0
         - neighbor 192.192.1.1 activate
         parents: router bgp 64949
     register: version
   - name: Second Task
     debug:
       var: version       
           
