---
- name: load new acl into device
  hosts: 27.27.27.209
  gather_facts: False
  connection: local
  tasks:
 - name: First Task
   cisco.ios.ios_acls:
     lines:
     - 10 permit ip 192.168.21.0 0.0.0.255 10.10.10.0 0.0.0.255
     - 20 permit ip 192.168.21.0 0.0.0.255 20.20.20.0 0.0.0.25
     - 30 permit ip 192.168.21.0 0.0.0.255 192.168.19.0 0.0.0.255
     - 40 permit ip host 172.16.144.26 host 172.16.134.16
     - 50 permit ip host 172.16.75.75 host 172.16.65.65
     parents: ip access-list extended EAS
   register: version
 - name: Second Task
   debug:
     var: version
