---
- name: First Play
  hosts: 27.27.27.213
  gather_facts: False
  connection: local
  tasks:
   - name: First Task
     ios_ping:
       dest: 20.20.20.20
       source: 10.10.10.10
       count: 50

     register: version
   - name: Second Task
     debug:
       var: version       
