---
- name: First Play
  hosts: 27.27.27.213
  gather_facts: False
  connection: local
  tasks:
   - name: First Task
     ios_config:
       lines:
         - encr 3des
         - hash md5
         - authentication pre-share
         - group 2
         - crypto isakmp key cisco123 address 192.192.1.2
       parents: crypto isakmp policy 100
     register: version
   - name: Second Task
     debug:
       var: version
