---
- name: First Play
  hosts: 27.27.27.213
  gather_facts: False
  connection: local
  tasks:
   - name: First Task
     ios_config:
       lines:
         - encr 3des
         - hash md5
         - authentication pre-share
         - group 2
         - crypto isakmp key cisco123 address 192.192.1.2
         - crypto ipsec transform-set TS esp-3des esp-md5-hmac
       parents: crypto isakmp policy 100
     register: version
   - name: Second Task
     debug:
       var: version
       
- name: Second Play
  hosts: 27.27.27.213
  gather_facts: False
  connection: local
  tasks:
   - name: First Task
     ios_config:
       lines:
         - permit ip 10.10.10.0 0.0.0.255 20.20.20.0 0.0.0.255
       parents: ip access-list extended VPN-TRAFFIC_1
     register: version
   - name: Second Task
     debug:
       var: version       

- name: Third Play
  hosts: 27.27.27.213
  gather_facts: False
  connection: local
  tasks:
   - name: First Task
     ios_config:
       lines:
         - set peer 1.1.1.2
         - set transform-set TS
         - match address VPN-TRAFFIC_1
       parents: crypto map CMAP 10 ipsec-isakmp
     register: version
   - name: Second Task
     debug:
       var: version
       
- name: Fourth Play
  hosts: 27.27.27.213
  gather_facts: False
  connection: local
  tasks:
   - name: First Task
     ios_config:
       lines:
         -  crypto map CMAP
       parents: interface Gi0/0/0.165
     register: version
   - name: Second Task
     debug:
       var: version       
       
- name: Fifth Play
  hosts: 27.27.27.209
  gather_facts: False
  connection: local
  tasks:
   - name: First Task
     ios_config:
       lines:
         - encr 3des
         - hash md5
         - authentication pre-share
         - group 2
         - crypto isakmp key cisco123 address 192.192.1.1
         - crypto ipsec transform-set TS esp-3des esp-md5-hmac
       parents: crypto isakmp policy 100
     register: version
   - name: Second Task
     debug:
       var: version
       
- name: Sixth Play
  hosts: 27.27.27.209
  gather_facts: False
  connection: local
  tasks:
   - name: First Task
     ios_config:
       lines:
         - permit ip 10.10.10.0 0.0.0.255 20.20.20.0 0.0.0.255
       parents: ip access-list extended VPN-TRAFFIC_1
     register: version
   - name: Second Task
     debug:
       var: version       

- name: Seventh Play
  hosts: 27.27.27.209
  gather_facts: False
  connection: local
  tasks:
   - name: First Task
     ios_config:
       lines:
         - set peer 1.1.1.2
         - set transform-set TS
         - match address VPN-TRAFFIC_1
       parents: crypto map CMAP 10 ipsec-isakmp
     register: version
   - name: Second Task
     debug:
       var: version
       
- name: Eighth Play
  hosts: 27.27.27.209
  gather_facts: False
  connection: local
  tasks:
   - name: First Task
     ios_config:
       lines:
         -  crypto map CMAP
       parents: interface Gi0/0/0.165
     register: version
   - name: Second Task
     debug:
       var: version

